---
# This set of include tasks should be considered internal to the role
# and not directly invoked by a playbook.  It is based on a dict structure
# with the root level key being "credentials".  The structure of the
# key is as follows:
#
#   credentials:
#     cli: [{...}, {...}],
#     snmp: [{...}, {...}]
#
# This task list will not check for the presence of the root key
# and assumes it to be present.  Currently the role entrypoint (main.yml)
# will only invoke these tasks if the "credentials" key is indeed present.
#

- name: configure global cli credentials
  ciscodevnet.ansible_dnac.cli_credentials:
    config: "{{ credentials.cli }}"
    update_password: "{{ update_password | default(omit) }}"
    state: "{{ state | default(omit) }}"
  when:
    - credentials.cli is defined


- name: configure global snmp credentials
  ciscodevnet.ansible_dnac.snmp_credentials:
    config: "{{ credentials.snmp }}"
    state: "{{ state | default(omit) }}"
  when:
    - credentials.snmp is defined


- name: configure global netconf credentials
  ciscodevnet.ansible_dnac.netconf_credentials:
    config: "{{ credentials.netconf }}"
    state: "{{ state | default(omit) }}"
  when:
    - credentials.netconf is defined
